platform:ios,'8.0'
pod 'AFNetworking', '~> 3.0.0-beta.3'
pod 'SDWebImage', '~> 3.7.3'
pod 'SDCycleScrollView', '~> 1.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SVProgressHUD', '~> 2.0-beta'
pod 'MJExtension', '~> 3.0.7'
pod 'UMengSocial', '~> 4.3'
